// ====================== 23B1023 =========================

// tool.cpp
//
// A tiny stub generator ("rpcgen"-style tool) for RPC assignment.
//
// It reads service.spec (a minimal IDL) and writes out:
//   - proxy.h / proxy.cpp : the CLIENT-SIDE stub. Contains a class
//        <Service>Proxy : public <Service> whose methods marshal
//        their arguments, ship them over a TCP socket to the server,
//        and unmarshal the result -- exactly the "socket calls here"
//        TODO left in abstract1.cpp, filled in automatically.
//   - stuff.h / stuff.cpp : the SERVER-SIDE skeleton. Contains a
//        function serve_<Service>() that accepts connections,
//        unmarshals a request, calls the REAL implementation object,
//        marshals the result, and sends it back.
//
// Usage: ./tool service.spec
//
// This only supports the shape of interface used in class
// (single int argument, single int return, one method) but is
// written so extending it to more methods/arg types is a matter of
// looping over more "method" lines instead of just method[0].

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

struct Method {
    std::string name;
    std::string retType;
    std::string argType;
};

struct ServiceSpec {
    std::string className;
    int port = 0;
    std::vector<Method> methods;
};

static ServiceSpec parseSpec(const std::string &path) {
    ServiceSpec spec;
    std::ifstream in(path);
    if (!in) {
        std::cerr << "tool: cannot open spec file " << path << std::endl;
        exit(1);
    }

    std::string line;
    while (std::getline(in, line)) {
        // strip comments / blank lines
        if (line.empty() || line[0] == '#') continue;

        std::istringstream iss(line);
        std::string keyword;
        iss >> keyword;

        if (keyword == "service") {
            iss >> spec.className;
        } else if (keyword == "port") {
            iss >> spec.port;
        } else if (keyword == "method") {
            Method m;
            iss >> m.name >> m.retType >> m.argType;
            spec.methods.push_back(m);
        }
    }
    return spec;
}

static void generateProxyHeader(const ServiceSpec &spec) {
    std::ofstream out("proxy.h");
    out << "// AUTO-GENERATED by tool.cpp from " << "service.spec" << " -- do not edit by hand\n";
    out << "#ifndef " << spec.className << "_PROXY_H\n";
    out << "#define " << spec.className << "_PROXY_H\n\n";
    out << "#include <string>\n";
    out << "#include \"" << spec.className << ".h\"\n\n";
    out << "// Client-side stub. Looks and behaves like a local " << spec.className
        << ", but every\n// call is shipped over the network to the real object on the server.\n";
    out << "class " << spec.className << "Proxy : public " << spec.className << " {\n";
    out << "    std::string serverIp;\n";
    out << "    int serverPort;\n";
    out << "public:\n";
    out << "    void setReal(const std::string &ip, int port);\n";
    for (auto &m : spec.methods) {
        out << "    " << m.retType << " " << m.name << "(" << m.argType << ");\n";
    }
    out << "};\n\n";
    out << "#endif\n";
}

static void generateProxySource(const ServiceSpec &spec) {
    std::ofstream out("proxy.cpp");
    out << "// AUTO-GENERATED by tool.cpp from service.spec -- do not edit by hand\n";
    out << "#include \"proxy.h\"\n";
    out << "#include <arpa/inet.h>\n";
    out << "#include <cstring>\n";
    out << "#include <iostream>\n";
    out << "#include <sstream>\n";
    out << "#include <sys/socket.h>\n";
    out << "#include <unistd.h>\n\n";

    out << "void " << spec.className << "Proxy::setReal(const std::string &ip, int port) {\n";
    out << "    serverIp = ip;\n";
    out << "    serverPort = port;\n";
    out << "}\n\n";

    for (auto &m : spec.methods) {
        out << m.retType << " " << spec.className << "Proxy::" << m.name << "(" << m.argType << " arg) {\n";
        out << "    // 1. connect to the server that hosts the real object\n";
        out << "    int sock = socket(AF_INET, SOCK_STREAM, 0);\n";
        out << "    sockaddr_in addr{};\n";
        out << "    addr.sin_family = AF_INET;\n";
        out << "    addr.sin_port = htons(serverPort);\n";
        out << "    inet_pton(AF_INET, serverIp.c_str(), &addr.sin_addr);\n";
        out << "    if (connect(sock, (sockaddr*)&addr, sizeof(addr)) < 0) {\n";
        out << "        std::cerr << \"" << spec.className << "Proxy: connect failed\" << std::endl;\n";
        out << "        close(sock);\n";
        out << "        return " << m.retType << "{};\n";
        out << "    }\n\n";
        out << "    // 2. marshal: turn the method name + args into a wire message\n";
        out << "    std::ostringstream req;\n";
        out << "    req << \"" << m.name << ":\" << arg << \"\\n\";\n";
        out << "    std::string reqStr = req.str();\n";
        out << "    send(sock, reqStr.c_str(), reqStr.size(), 0);\n\n";
        out << "    // 3. unmarshal: read the result the server sends back\n";
        out << "    char buffer[256] = {0};\n";
        out << "    recv(sock, buffer, sizeof(buffer) - 1, 0);\n";
        out << "    close(sock);\n\n";
        out << "    return static_cast<" << m.retType << ">(atoi(buffer));\n";
        out << "}\n\n";
    }
}

static void generateStuffHeader(const ServiceSpec &spec) {
    std::ofstream out("stuff.h");
    out << "// AUTO-GENERATED by tool.cpp from service.spec -- do not edit by hand\n";
    out << "#ifndef " << spec.className << "_STUFF_H\n";
    out << "#define " << spec.className << "_STUFF_H\n\n";
    out << "#include \"" << spec.className << ".h\"\n\n";
    out << "// Server-side skeleton/dispatcher. Given a REAL implementation object\n";
    out << "// and a port, this listens forever, and for every incoming connection:\n";
    out << "// reads the request, unmarshals it, calls the matching method on\n";
    out << "// impl, marshals the result, and sends it back.\n";
    out << "void serve_" << spec.className << "(" << spec.className << " *impl, int port);\n\n";
    out << "#endif\n";
}

static void generateStuffSource(const ServiceSpec &spec) {
    std::ofstream out("stuff.cpp");
    out << "// AUTO-GENERATED by tool.cpp from service.spec -- do not edit by hand\n";
    out << "#include \"stuff.h\"\n";
    out << "#include <arpa/inet.h>\n";
    out << "#include <cstring>\n";
    out << "#include <iostream>\n";
    out << "#include <sstream>\n";
    out << "#include <sys/socket.h>\n";
    out << "#include <unistd.h>\n\n";

    out << "void serve_" << spec.className << "(" << spec.className << " *impl, int port) {\n";
    out << "    int serverSocket = socket(AF_INET, SOCK_STREAM, 0);\n";
    out << "    int opt = 1;\n";
    out << "    setsockopt(serverSocket, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));\n\n";
    out << "    sockaddr_in addr{};\n";
    out << "    addr.sin_family = AF_INET;\n";
    out << "    addr.sin_port = htons(port);\n";
    out << "    addr.sin_addr.s_addr = INADDR_ANY;\n\n";
    out << "    bind(serverSocket, (sockaddr*)&addr, sizeof(addr));\n";
    out << "    listen(serverSocket, 5);\n";
    out << "    std::cout << \"" << spec.className << " server listening on port \" << port << std::endl;\n\n";
    out << "    while (true) {\n";
    out << "        int client = accept(serverSocket, nullptr, nullptr);\n";
    out << "        if (client < 0) continue;\n\n";
    out << "        char buffer[256] = {0};\n";
    out << "        recv(client, buffer, sizeof(buffer) - 1, 0);\n";
    out << "        std::string req(buffer);\n\n";
    out << "        // unmarshal: split \"methodName:arg\"\n";
    out << "        size_t colon = req.find(':');\n";
    out << "        std::string methodName = req.substr(0, colon);\n";
    out << "        int arg = atoi(req.substr(colon + 1).c_str());\n\n";
    out << "        int result = 0;\n";
    for (size_t i = 0; i < spec.methods.size(); ++i) {
        auto &m = spec.methods[i];
        out << "        " << (i == 0 ? "" : "else ") << "if (methodName == \"" << m.name << "\") {\n";
        out << "            result = impl->" << m.name << "(arg);\n";
        out << "        }\n";
    }
    out << "\n";
    out << "        // marshal: send the result back as text\n";
    out << "        std::ostringstream resp;\n";
    out << "        resp << result;\n";
    out << "        std::string respStr = resp.str();\n";
    out << "        send(client, respStr.c_str(), respStr.size(), 0);\n\n";
    out << "        close(client);\n";
    out << "    }\n";
    out << "}\n";
}

int main(int argc, char *argv[]) {
    std::string specFile = "service.spec";
    if (argc > 1) specFile = argv[1];

    ServiceSpec spec = parseSpec(specFile);
    if (spec.className.empty() || spec.methods.empty()) {
        std::cerr << "tool: spec file missing 'service' or 'method' lines" << std::endl;
        return 1;
    }

    generateProxyHeader(spec);
    generateProxySource(spec);
    generateStuffHeader(spec);
    generateStuffSource(spec);

    std::cout << "tool: generated proxy.h, proxy.cpp, stuff.h, stuff.cpp for service '"
              << spec.className << "' (port " << spec.port << ")" << std::endl;
    return 0;
}
